# Site settings
theme: minima  # This will ensure the basic Jekyll theme is available
title: Tula Masterman
email: tula@themastermans.com
description: >-
  Personal portfolio for Tula Masterman, featuring research papers, 
  videos, blog posts, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tmasterman.github.io" # your site's production URL
twitter_username: tula.masterman
github_username:  tmasterman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom Settings
subtitle: AI Solutions Leader & Applied Data Scientist
experience_description: >-
  For over five years, I've pursued my passion for data science and AI, including three years leading research and innovation initiatives. I've trained custom models for computer vision and natural language based tasks, and built generative AI solutions that pioneered innovative data pre-processing techniques and agent patterns using models from the world's leading providers like OpenAI, Meta, and Anthropic. 
  <br><br>
  I've collaborated with incredible researchers, technical teams, and partners like Microsoft to deliver high-impact solutions that solve complex business challenges. I publish research papers, write articles frequently selected as Editor's Picks in Towards Data Science, and create educational videos that have reached over 10,000 industry professionals.

contact_description: >-
  I'm always interested in connecting with like-minded professionals. Feel free to reach out through any of the platforms below.

# Collections
# collections:
#   research:
#     output: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/